spring:
  profiles:
    active: local
  datasource:
    url: jdbc:h2:tcp://localhost/~/workspace/h2-repository/security-study;MODE=MySQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
#  security:
#    user:
#      name: test
#      password: 123
#      roles: ADMIN

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 100
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

logging.level:
  com.github.springsecuritystudy : debug
  org.hibernate.SQL: debug
  org.hibernate.type: trace